"use client";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Boxes, CheckCircle2, ShieldCheck, ShipWheel, Sparkles } from "lucide-react";
import { CargoShip } from "@/components/ship";
const roles = [
 {title:"Trader", desc:"I want to book cargo space.", icon:Boxes, href:"/dashboard/trader", tone:"bg-sky"},
 {title:"Logistics Provider", desc:"I have available container space.", icon:ShipWheel, href:"/dashboard/provider", tone:"bg-orange"},
 {title:"Admin", desc:"Approve providers and monitor the platform.", icon:ShieldCheck, href:"/dashboard/admin", tone:"bg-navy"}
];
export default function Home() { return <main className="overflow-hidden bg-[#f5f9fc] text-ink"><section className="grid-pattern relative min-h-[710px] overflow-hidden"><div className="absolute right-[-10%] top-24 h-96 w-96 rounded-full bg-sky/10 blur-3xl"/><nav className="relative mx-auto flex max-w-7xl items-center justify-between px-6 py-6 md:px-10"><Link href="/" className="flex items-center gap-2 font-bold text-navy"><span className="grid h-9 w-9 place-items-center rounded-xl bg-navy text-white"><ShipWheel size={20}/></span> Cargo<span className="-ml-2 text-sky">Connect</span></Link><div className="hidden gap-8 text-sm font-medium text-slate-600 md:flex"><a href="#how">How it works</a><a href="#roles">Solutions</a><a href="#contact">Contact</a></div><Link href="/login" className="rounded-full border border-navy px-5 py-2 text-sm font-semibold text-navy hover:bg-navy hover:text-white">Sign in</Link></nav>
<div className="relative mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-16 md:grid-cols-2 md:px-10"><div><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="mb-5 inline-flex items-center gap-2 rounded-full border border-sky/20 bg-white/80 px-4 py-2 text-xs font-bold text-navy"><Sparkles size={14} className="text-orange"/> The intelligent cargo marketplace</motion.div><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="max-w-xl text-5xl font-bold leading-[1.05] tracking-tight text-navy md:text-7xl">Every container has <span className="text-sky">room</span> for growth.</motion.h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-slate-600">Discover unused capacity, book with confidence, and move your business forward. Freight collaboration made beautifully simple.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/dashboard/trader" className="flex items-center gap-2 rounded-full bg-navy px-6 py-3.5 text-sm font-bold text-white shadow-glow hover:bg-[#0a4775]">Find cargo space <ArrowRight size={17}/></Link><a href="#how" className="rounded-full border border-slate-300 bg-white px-6 py-3.5 text-sm font-bold text-navy">See how it works</a></div><div className="mt-10 flex gap-6 text-sm"><span className="flex items-center gap-2 font-medium"><CheckCircle2 size={18} className="text-sky"/> Vetted providers</span><span className="flex items-center gap-2 font-medium"><CheckCircle2 size={18} className="text-sky"/> Secure booking</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="glass relative rounded-[2rem] p-8 shadow-glow"><div className="mb-7 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Live shipment</p><p className="mt-1 font-bold text-navy">Mumbai → Rotterdam</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">On schedule</span></div><div className="relative h-52 overflow-hidden rounded-2xl bg-gradient-to-b from-[#dff5ff] to-[#8bd2f4]"><div className="absolute inset-x-0 bottom-0 h-12 bg-sky/50"/><div className="absolute bottom-7 left-1/2 -translate-x-1/2"><CargoShip/></div></div><div className="mt-6 grid grid-cols-3 gap-3 text-center"><div><p className="text-xl font-bold text-navy">66</p><p className="text-xs text-slate-500">Boxes free</p></div><div className="border-x border-slate-200"><p className="text-xl font-bold text-navy">18 Aug</p><p className="text-xs text-slate-500">Departure</p></div><div><p className="text-xl font-bold text-orange">$46</p><p className="text-xs text-slate-500">per box</p></div></div></div></div></div></section>
<section id="roles" className="mx-auto max-w-7xl px-6 py-24 md:px-10"><div className="mb-10 max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-sky">One platform, clear roles</p><h2 className="mt-3 text-4xl font-bold text-navy">Move cargo together.</h2></div><div className="grid gap-5 md:grid-cols-3">{roles.map((role,i)=><motion.div key={role.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} transition={{delay:i*.1}} viewport={{once:true}} whileHover={{y:-8}} className="rounded-3xl border border-slate-100 bg-white p-7 shadow-sm"><span className={`mb-8 grid h-14 w-14 place-items-center rounded-2xl ${role.tone} text-white`}><role.icon size={28}/></span><h3 className="text-xl font-bold text-navy">{role.title}</h3><p className="mt-3 min-h-12 text-slate-500">{role.desc}</p><Link href={role.href} className="mt-8 flex items-center gap-2 font-bold text-navy hover:text-sky">{role.title === "Admin" ? "Admin login" : "Enter dashboard"} <ArrowRight size={17}/></Link></motion.div>)}</div></section>
<section id="how" className="bg-navy px-6 py-20 text-white md:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-widest text-sky">Shared capacity, simplified</p><div className="mt-6 grid gap-9 md:grid-cols-3">{[["01","Search a lane","Find capacity on your preferred route."],["02","Book securely","Reserve only the space you need."],["03","Ship smarter","Stay informed from booking to berth."]].map(([n,t,d])=><div key={n}><p className="text-5xl font-bold text-sky/30">{n}</p><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-slate-300">{d}</p></div>)}</div></div></section><footer id="contact" className="flex flex-col items-center justify-between gap-3 px-10 py-8 text-sm text-slate-500 md:flex-row"><span>© 2026 CargoConnect. Freight, connected.</span><span>contact@cargoconnect.io · +1 800 334 9801</span></footer></main> }
