"use client";
import { motion } from "framer-motion";

function IsoContainer({color, className=""}:{color:string;className?:string}) { return <div className={`relative h-12 w-16 ${className}`}><div className="isometric-top absolute inset-x-0 top-0 h-5" style={{backgroundColor:color, filter:"brightness(1.22)"}}/><div className="isometric-side absolute inset-x-0 top-4 h-9" style={{backgroundColor:color}}/><div className="absolute left-2 top-6 h-5 w-px bg-white/35"/><div className="absolute left-7 top-7 h-5 w-px bg-white/35"/><div className="absolute left-12 top-8 h-5 w-px bg-white/35"/></div> }
export function IsometricShip() { return <div className="relative h-[380px] w-full overflow-hidden rounded-[2rem] border border-white/80 bg-gradient-to-b from-[#f2fbff] via-[#d6f0fb] to-[#8acbed] shadow-[0_30px_80px_rgba(16,96,157,.18)]">
 <div className="cloud-drift absolute left-10 top-12 h-6 w-20 rounded-full bg-white/80 shadow-sm after:absolute after:-right-3 after:bottom-0 after:h-8 after:w-8 after:rounded-full after:bg-white/80"/><div className="cloud-drift absolute right-16 top-20 h-4 w-14 rounded-full bg-white/70" style={{animationDelay:"-4s"}}/>
 <div className="absolute inset-x-0 bottom-0 h-36 overflow-hidden bg-[#5fb7e8]"><div className="wave-flow absolute -left-10 top-3 h-5 w-[calc(100%+100px)] opacity-50" style={{backgroundImage:"radial-gradient(ellipse at center, transparent 0 48%, #e4f8ff 50% 56%, transparent 58%)",backgroundSize:"54px 18px"}}/><div className="absolute inset-x-0 bottom-0 h-20 bg-[#3299d5]"/></div>
 <motion.div animate={{y:[0,-7,0], rotate:[0,.5,0]}} transition={{duration:4,repeat:Infinity,ease:"easeInOut"}} className="absolute bottom-20 left-1/2 h-48 w-[330px] -translate-x-1/2">
  <div className="absolute bottom-3 left-3 h-20 w-[305px] rounded-b-[4rem] bg-[#0B1F3A] shadow-xl" style={{clipPath:"polygon(0 0,100% 0,85% 100%,15% 100%)"}}/><div className="absolute bottom-2 left-9 h-5 w-[255px] rounded-b-full bg-[#1c5c91]"/>
  <div className="absolute bottom-[75px] left-8 h-7 w-[290px] bg-[#174b76]"/><div className="absolute bottom-[99px] left-12 flex items-end gap-1"><IsoContainer color="#F2994A"/><IsoContainer color="#2F80ED" className="-mb-4"/><IsoContainer color="#174b76"/><IsoContainer color="#F2994A" className="-mb-4"/></div>
  <div className="absolute bottom-[104px] left-[92px] flex gap-1"><IsoContainer color="#2F80ED"/><IsoContainer color="#F2994A"/></div><div className="absolute bottom-[143px] left-[128px] h-12 w-16 rounded-t-lg border-b-4 border-[#d6e9f3] bg-white"><div className="mx-auto mt-3 grid w-9 grid-cols-3 gap-1"><i className="h-2 bg-sky/40"/><i className="h-2 bg-sky/40"/><i className="h-2 bg-sky/40"/></div></div>
 </motion.div><div className="absolute bottom-7 left-7 rounded-full bg-white/85 px-3 py-1.5 text-[11px] font-bold text-navy shadow-sm">● LIVE · MV PACIFIC STAR</div></div> }
