"use client";
import { motion } from "framer-motion";
import Image from "next/image";

export function LivingHero(){return <motion.div whileHover={{scale:1.008}} className="relative isolate h-[430px] overflow-hidden rounded-[2.25rem] border border-white/80 bg-[#dff4ff] shadow-[0_36px_90px_rgba(11,31,58,.16)]">
  <div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(rgba(47,128,237,.25) 1px,transparent 1px),linear-gradient(90deg,rgba(47,128,237,.25) 1px,transparent 1px)",backgroundSize:"38px 38px"}}/>
  <motion.div animate={{x:[-30,35,-30]}} transition={{duration:16,repeat:Infinity,ease:"easeInOut"}} className="absolute left-4 top-16 h-8 w-28 rounded-full bg-white/85 after:absolute after:bottom-0 after:right-5 after:h-9 after:w-9 after:rounded-full after:bg-white/85"/><motion.div animate={{x:[20,-45,20]}} transition={{duration:21,repeat:Infinity,ease:"easeInOut"}} className="absolute right-8 top-28 h-4 w-16 rounded-full bg-white/70"/>
  <div className="absolute left-8 top-9 font-mono text-[9px] font-bold tracking-[.28em] text-sky/70">MUMBAI PORT / 19.0760° N</div>
  <svg viewBox="0 0 500 430" className="absolute inset-0 h-full w-full" aria-hidden="true"><motion.path d="M40 270 C 135 200, 225 310, 400 185" fill="none" stroke="#2F80ED" strokeDasharray="5 10" strokeWidth="2" initial={{pathLength:0,opacity:0}} animate={{pathLength:1,opacity:.55}} transition={{duration:2.2,repeat:Infinity,repeatType:"reverse",ease:"easeInOut"}}/><circle cx="40" cy="270" r="5" fill="#F2994A"/><circle cx="400" cy="185" r="5" fill="#27AE60"/></svg>
  <motion.div animate={{y:[0,-9,0],rotate:[-2,2,-2]}} transition={{duration:7,repeat:Infinity,ease:"easeInOut"}} className="absolute right-7 top-11 h-12 w-16"><div className="isometric-top absolute inset-x-0 top-0 h-5 bg-orange"/><div className="isometric-side absolute inset-x-0 top-4 h-9 bg-[#cf7029]"/></motion.div>
  <div className="absolute bottom-0 left-0 right-0 h-[142px] overflow-hidden bg-[#54b5e7]"><div className="wave-flow absolute -left-12 top-2 h-6 w-[calc(100%+120px)] opacity-55" style={{backgroundImage:"radial-gradient(ellipse at center,transparent 0 48%,#effbff 50% 56%,transparent 58%)",backgroundSize:"54px 18px"}}/><div className="absolute bottom-0 h-16 w-full bg-[#298ec9]"/></div>
  <div className="absolute bottom-[123px] left-5 h-20 w-20 opacity-75"><div className="absolute bottom-0 h-2 w-20 bg-[#0B1F3A]"/><div className="absolute bottom-2 left-2 h-16 w-1 bg-[#0B1F3A]"/><div className="absolute bottom-[57px] left-2 h-1 w-14 origin-left rotate-[18deg] bg-[#0B1F3A]"/><motion.div animate={{x:[0,16,0]}} transition={{duration:6,repeat:Infinity,ease:"easeInOut"}} className="absolute bottom-[36px] left-10 h-5 w-6 border border-navy bg-orange"/></div>
  <motion.div animate={{y:[0,-6,0],rotate:[0,.28,0]}} transition={{duration:4,repeat:Infinity,ease:"easeInOut"}} className="absolute bottom-[20px] left-1/2 h-52 w-[390px] -translate-x-1/2 drop-shadow-2xl"><Image src="/cargo-connect-vessel.png" alt="CargoConnect container vessel" fill priority className="object-contain mix-blend-multiply"/></motion.div><motion.div animate={{x:[0,17,0],y:[0,-3,0]}} transition={{duration:9,repeat:Infinity,ease:"easeInOut"}} className="absolute bottom-24 right-5 rounded-full border border-white/70 bg-white/80 px-3 py-1.5 text-[10px] font-bold tracking-wide text-navy shadow-sm">ROUTE CONFIRMED</motion.div>
  <div className="absolute bottom-5 left-5 flex gap-2"><span className="rounded-full bg-navy/90 px-3 py-1.5 text-[10px] font-bold tracking-wide text-white">● LIVE FLEET</span><span className="rounded-full bg-white/85 px-3 py-1.5 text-[10px] font-bold tracking-wide text-navy">MV PACIFIC STAR</span></div>
 </motion.div>}
